### ISSUE TITLE
Cannot run php ssh2_exec() command with sshd-shell

### ISSUE THREAD

**Issue by smdark** [anand1st/sshd-shell-spring-boot#5]
Hello I am using sshd-shell (version 2.5) for controlling my console application via SSH protocol. 
I want to control console app from PHP app using ssh2 library, but for some reason i can't use command ssh2_exec(). Before sshd-shell  I was using spring-boot-starter-remote-shell which was working correctly with ssh2_exec() command. 

I am getting this error on  PHP side:

`
ssh2_exec(): Unable to request command execution on remote host
`

And on Java side I get this log entry

`
2017-11-13 14:14:52.347  INFO 18660 --- []-nio2-thread-3] o.a.s.s.session.ServerUserAuthService    : Session admin@/127.0.0.1:49564 authenticated
`

`
2017-11-13 14:14:52.365  WARN 18660 --- []-nio2-thread-5] o.a.sshd.server.channel.ChannelSession   : handleExec(ChannelSession[id=0, recipient=0]-ServerSessionImpl[admin@/127.0.0.1:49564]) No command factory for command: help
`

When I run ssh2_shell() command i can get output from sshd-shell

>OUTPUT START

Enter \'help\' for a list of supported commands

[?2004htest> help

[?2004lSupported Commands

help                Show list of help commands

Supported post processors for output

h <arg>             Highlights <arg> in response output of command execution

Example usage: help | h exit

[?2004lExiting shell

> OUTPUT END

**Question, is it possible to make sshd-shell to work with ssh2_exec() command?**

I will appreciate any help on this question.
Thanks in advance

**Comment by anand1st** [comment]
Please try using ssh2_shell() with version 2.5 of sshd-shell-spring-boot-starter. Alternatively, you can upgrade to version 2.6 as it should support ssh2_exec() now.

**Comment by smdark** [comment]
Hi thanks for fast response I updated sshd-shell till 2.6 version now PHP do not return ssh2_exec() error, but seems something is not still working correctly, first when I try to read stream PHP hangs till server timeout (504 Gateway Time-out) and second when I do not wait response but just exec scheduler start command and go look scheduler status via putty its not started that means command was not executed.

If i do not wait stream exception occurs (not always) in Java log:

Authenticated successfully
`2017-11-14 08:32:41.551  INFO 1116 --- []-nio2-thread-3] o.a.s.s.session.ServerUserAuthService    : Session admin@/127.0.0.1:49826 authenticated`

Exception:

```
Exception in thread "ssh-cli admin" org.jline.reader.EndOfFileException: org.jline.utils.ClosedException: InputStreamReader is closed.
	at org.jline.keymap.BindingReader.readCharacter(BindingReader.java:140)
	at org.jline.keymap.BindingReader.readBinding(BindingReader.java:109)
	at org.jline.keymap.BindingReader.readBinding(BindingReader.java:60)
	at org.jline.reader.impl.LineReaderImpl.readBinding(LineReaderImpl.java:724)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:526)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:390)
	at sshd.shell.springboot.console.TerminalProcessor.processUserInput(TerminalProcessor.java:83)
	at sshd.shell.springboot.console.TerminalProcessor.processInputs(TerminalProcessor.java:57)
	at sshd.shell.springboot.server.SshSessionInstance.run(SshSessionInstance.java:68)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.jline.utils.ClosedException: InputStreamReader is closed.
	at org.jline.utils.InputStreamReader.read(InputStreamReader.java:191)
	at org.jline.utils.NonBlockingReader.run(NonBlockingReader.java:276)
	... 1 more
```

For testing SSHD-Shell I am using this piece of PHP code:

```
$test = ssh2_connect('127.0.0.1', 8437);
ssh2_auth_password($test, 'admin', 'admin');
$stream = ssh2_exec($test, "scheduler start");

stream_set_blocking($stream, true);
$stream_out = ssh2_fetch_stream($stream, SSH2_STREAM_STDIO);
echo stream_get_contents($stream_out);
```

On Ubuntu server this code is working just fine. If i exec `$stream = ssh2_exec($test, "ls -l");` I get response `total 0`  which is correct response.

Is there still something wrong with sshd-shell?

Thanks in advance

**Comment by anand1st** [comment]
I've not had any experience with ssh2_exec hence I am not sure I can help. I have tested with SSH exec using JSch (which is a Java client for SSH) and it works fine in my unit tests. However, I've had to add return carriage after the command for it to work with JSch in my case.

Might this work in your case?

**Comment by smdark** [comment]
I tried to add return carriage but without any success. I'm now using other method to connecting and executing commands via sshd-shell, new method seems to work. So for now i will leave ssh2_exec(). 
Any way thanks for your fast response and help. 👍
